spring:
  application:
    name: notfound
  
  datasource:
    url: jdbc:postgresql://database:5432/parking_db
    username: parking_user
    password: parking_pass
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    defer-datasource-initialization: true
  
  sql:
    init:
      mode: always

server:
  port: 8080

logging:
  level:
    com.esgi.notfound: DEBUG
    org.hibernate.SQL: DEBUG
    com.zaxxer.hikari: DEBUG